# Generated by Django 4.2.4 on 2023-10-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0002_comic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='dateofbirth',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='username',
        ),
        migrations.AlterField(
            model_name='signup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
