# Generated by Django 4.2.4 on 2023-10-12 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0003_remove_signup_dateofbirth_remove_signup_username_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signup',
            new_name='Signup1',
        ),
        migrations.AlterModelTable(
            name='signup1',
            table='Signup1_table',
        ),
    ]
