# Generated by Django 4.2.4 on 2023-10-12 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0004_rename_signup_signup1_alter_signup1_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup1',
            old_name='email',
            new_name='username',
        ),
    ]
